"""Emit publication-style LaTeX tables (booktabs) from pandas DataFrames."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


def _escape_latex(s: str) -> str:
    return (
        str(s)
        .replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("_", "\\_")
        .replace("#", "\\#")
    )


def _fmt_cell(v) -> str:
    if pd.isna(v):
        return "---"
    if isinstance(v, (bool, np.bool_)):
        return "true" if v else "false"
    if isinstance(v, (int, np.integer)):
        return str(int(v))
    if isinstance(v, (float, np.floating)):
        return f"{float(v):.4f}"
    return _escape_latex(v)


def dataframe_to_booktabs(
    df: pd.DataFrame,
    path: Path,
    *,
    caption: str,
    label: str,
) -> None:
    """Write a minimal booktabs tabular (no tabularx dependency)."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "% Auto-generated by llm_comparison_lite",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{{_escape_latex(caption)}}}",
        f"\\label{{{label}}}",
        "\\begin{tabular}{" + "l" * len(df.columns) + "}",
        "\\toprule",
    ]

    cols = list(df.columns)
    lines.append(" & ".join(_escape_latex(c) for c in cols) + " \\\\")
    lines.append("\\midrule")

    for _, row in df.iterrows():
        cells = []
        for c in cols:
            cells.append(_fmt_cell(row[c]))
        lines.append(" & ".join(cells) + " \\\\")

    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")
